# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique='True'),
        ),
    ]
